application: dpc-montyhall
version: 5
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: montyhall.app

libraries:
- name: jinja2
  version: latest
